#!/usr/bin/env bash

echo "[projark] Legacy bash wrapper has been archived at legacy/projark_legacy.sh"
echo "[projark] Please use the Python CLI: projark <deposit|retrieve> ..."
python -m parkit.projark "$@"
